#!/bin/bash

# installs the scripts in this repo to the ~/.bin directory
# and adds that directory into the $PATH

# make the directory if it doesn't exist
mkdir -p ~/.bin

# copy the files in ./bin/* to ~/.bin/.


# update the ~/.zshrc to include ~/.bin in the $PATH
